services:
  db:
    container_name: db
    image: postgres:14
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=it21774
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 2
    volumes:
      - './assets/db:/docker-entrypoint-initdb.d'
      - 'pgdata14:/var/lib/postgresql/data'
    networks:
      - demo_network
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"   # API port
      - "9001:9001"   # Browser Console port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_URL: http://localhost:9000
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - demo_network
  spring:
    container_name: spring
    image: "ghcr.io/kevinstana/ldap-spring"
    ports:
      - "8080:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/it21774
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - demo_network
  front:
    container_name: front
    image: "ghcr.io/kevinstana/next"
    environment:
      - AUTH_SECRET=348412897bfab5dfbd754c94dfdc4be45909f44db07c74494d75d514bd91f935
      - AUTH_TRUST_HOST=true
      - API_URL=http://spring:9090/api
    restart: always
    ports:
        - 3000:3000
    networks:
      - demo_network

volumes:
    pgdata14:
    minio-data:

networks:
  demo_network:
    external: false
    name: demo_network
