INSERT INTO courses (name, url) VALUES
    ('Υπολογιστικά Μαθηματικά', 'https://eclass.hua.gr/courses/DIT202/'),
    ('Ψηφιακή Τεχνολογία και Εφαρμογές Τηλεματικής', null),
    ('Προγραμματισμός Ι', 'https://eclass.hua.gr/courses/DIT135/'),
    ('Λογική Σχεδίαση', 'https://eclass.hua.gr/courses/DIT131/'),
    ('Διακριτά Μαθηματικά', 'https://eclass.hua.gr/courses/DIT144/'),

    ('Πιθανότητες', 'https://eclass.hua.gr/courses/DIT155/'),
    ('Αριθμητική Ανάλυση', 'https://eclass.hua.gr/courses/DIT154/'),
    ('Προγραμματισμός ΙΙ', 'https://eclass.hua.gr/courses/DIT116/'),
    ('Αρχιτεκτονική Υπολογιστών', 'https://eclass.hua.gr/courses/DIT106/'),
    ('Αντικειμενοστρεφής Προγραμματισμός Ι', 'https://eclass.hua.gr/courses/DIT112/'),

    ('Στατιστική', 'https://eclass.hua.gr/courses/DIT142/'),
    ('Αντικειμενοστρεφής Προγραμματισμός ΙΙ', 'https://eclass.hua.gr/courses/DIT267/'),
    ('Δομές Δεδομένων', 'https://eclass.hua.gr/courses/DIT141/'),
    ('Λειτουργικά Συστήματα', 'https://eclass.hua.gr/courses/DIT136/'),
    ('Δίκτυα Υπολογιστών', 'https://eclass.hua.gr/courses/DIT150/'),

    ('Μεθοδολογία Επιστημονικής Έρευνας', 'https://eclass.hua.gr/courses/DIT157/'),
    ('Σήματα και Συστήματα', 'https://eclass.hua.gr/courses/DIT108/'),
    ('Βάσεις Δεδομένων', 'https://eclass.hua.gr/courses/DIT105/'),
    ('Ανάλυση Συστημάτων και Τεχνολογία Λογισμικού', 'https://eclass.hua.gr/courses/DIT225/'),
    ('Τεχνολογίες Εφαρμογών Ιστού', 'https://eclass.hua.gr/courses/DIT102/'),
    
    
    ('Σχεδίαση Βάσεων Δεδομένων και Κατανεμημένες Βάσεις Δεδομένων', 'https://eclass.hua.gr/courses/DIT128/'),
    ('Διαχείριση Επιχειρηματικών Διαδικασιών στην Εφοδιαστική Αλυσίδα', 'https://eclass.hua.gr/courses/DIT222/'),
    ('Τεχνολογίες Διαδικτύου', 'https://eclass.hua.gr/courses/DIT299/'),
    ('Πληροφορική και Εκπαίδευση', 'https://eclass.hua.gr/courses/DIT127/'),
    ('Ανάπτυξη Κινητών Εφαρμογών', 'https://eclass.hua.gr/courses/DIT117/'),
    ('Οικονομικά της Ψηφιακής Τεχνολογίας', 'https://eclass.hua.gr/courses/DIT194/'),
    ('Προηγμένα Θέματα Λειτουργικών Συστημάτων', null),
    ('Καινοτομία και Επιχειρηματικότητα', 'https://eclass.hua.gr/courses/LANGUAGES108/'),
    ('Τηλεπικοινωνιακά Συστήματα', 'https://eclass.hua.gr/courses/DIT149/'),
    ('Κατανεμημένα Συστήματα', 'https://eclass.hua.gr/courses/DIT138/'),
    ('Πληροφοριακά Συστήματα', 'https://eclass.hua.gr/courses/DIT234/'),

    ('Αλγόριθμοι και Πολυπλοκότητα', 'https://eclass.hua.gr/courses/DIT110/'),
    ('Προσομοίωση', 'https://eclass.hua.gr/courses/DIT113/'),
    ('Τεχνητή Νοημοσύνη', 'https://eclass.hua.gr/courses/DIT231/'),
    ('Εφαρμογές Ηλεκτρονικής και Διαδίκτυο των Πραγμάτων', 'https://eclass.hua.gr/courses/DIT125/'),
    ('Βασικές έννοιες και εργαλεία DevOps', 'https://eclass.hua.gr/courses/DIT250/'),
    ('Συστήματα Λήψης Αποφάσεων', 'https://eclass.hua.gr/courses/DIT228/'),
    ('Διδακτική της Πληροφορικής', 'https://eclass.hua.gr/courses/DIT201/'),
    ('Υπηρεσίες και Συστήματα Διαδικτύου', 'https://eclass.hua.gr/courses/DIT220/'),
    ('Οπτικές Επικοινωνίες', 'https://eclass.hua.gr/courses/DIT126/'),
    ('Ψηφιακή Επεξεργασία Εικόνας και Εφαρμογές', 'https://eclass.hua.gr/courses/DIT271/'),

    ('Εξόρυξη Δεδομένων', 'https://eclass.hua.gr/courses/DIT129/'),
    ('Απόδοση Συστημάτων', 'https://eclass.hua.gr/courses/DIT145/'),
    ('Συστήματα Κινητών Επικοινωνιών', 'https://eclass.hua.gr/courses/DIT151/'),
    ('Τεχνοοικονομική Ανάλυση Πληροφοριακών, Τηλεματικών και Τηλεπικοινωνιακών Συστημάτων', null),
    ('Παράλληλοι Υπολογιστές και Αλγόριθμοι', 'https://eclass.hua.gr/courses/DIT139/'),
    ('Κοινωνία και ΤΠΕ', 'https://eclass.hua.gr/courses/DIT158/'),
    ('Μηχανική Μάθηση και Εφαρμογές', 'https://eclass.hua.gr/courses/DIT232/'),
    ('Διδακτική ρομποτικής και εκπαίδευση STEM', 'https://eclass.hua.gr/courses/DIT239/'),
    ('Τεχνολογίες Γραφημάτων και Εφαρμογές', 'https://eclass.hua.gr/courses/DIT263/'),
    ('Διαχείριση Υποδομών Νέφους', null),
    ('Επικοινωνία Ανθρώπου-Μηχανής', 'https://eclass.hua.gr/courses/DIT265/'),
    ('Ασφάλεια Πληροφοριακών Συστημάτων', 'https://eclass.hua.gr/courses/DIT203/'),

    ('Προγραμματισμός Συστημάτων', 'https://eclass.hua.gr/courses/DIT137/'),
    ('Πληροφοριακά Συστήματα και Ηλεκτρονικό Επιχειρείν', 'https://eclass.hua.gr/courses/DIT277/'),
    ('Διοίκηση Έργων Πληροφορικής', 'https://eclass.hua.gr/courses/DIT227/'),
    ('Εφαρμογές Τηλεματικής στις Μεταφορές και την Υγεία', 'https://eclass.hua.gr/courses/DIT159/'),
    ('Μεταγλωττιστές', 'https://eclass.hua.gr/courses/DIT107/'),
    ('Παιδαγωγική Ψυχολογία', null),
    ('Κρυπτογραφία', 'https://eclass.hua.gr/courses/DIT208/'),
    ('Διαχείριση Δικτύων Βασισμένων στο Λογισμικό', 'https://eclass.hua.gr/courses/DIT289/'),
    ('Προηγμένα Θέματα Ψηφιακής Σχεδίασης', null);
