services:
  db:
    image: postgres:14
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=it21774
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 2
    volumes:
      - './assets/db:/docker-entrypoint-initdb.d'
      - 'pgdata14:/var/lib/postgresql/data'
  spring:
    image: "spring-ldap"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/it21774
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/api/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 2

volumes:
    pgdata14: